// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nwqxsdztylcewebcjsdi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im53cXhzZHp0eWxjZXdlYmNqc2RpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAyNDAyMTAsImV4cCI6MjA2NTgxNjIxMH0.O6iO7mVg-g0IoegPmU5xtsdBw9bO1qzbCDt6o3o0v8Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);